language: python

python:
  - "3.8"

install:
  - pip install -r requirements.txt

addons:
  postgresql: 13
  apt:
    packages:
    - postgresql-13
env:
  global:
  - PGPORT=5433
  - SECRET_KEY='secret_key'

services:
  - postgresql

before_install:
  # Use trust instead of peer authentication:
  - >-
    sudo sed -i
    -e '/local.*peer/s/postgres/all/'
    -e 's/peer\|md5/trust/g'
    /etc/postgresql/13/main/pg_hba.conf
  # Restart the PostgreSQL service:
  - sudo service postgresql@13-main restart

before_script:
  - psql -p 5433 -U postgres -c 'CREATE DATABASE test_database;'
  - psql -p 5433 -U postgres -f test_data.sql -d test_database

script:
  - python manage.py test --keepdb
